# Generated by Django 5.2.8 on 2025-11-21 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='fecha_corte',
        ),
        migrations.RemoveField(
            model_name='card',
            name='fecha_limite_pago',
        ),
        migrations.AddField(
            model_name='card',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='dia_corte',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='dia_limite_pago',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
